{% set python_min = "3.10" %}
{% set name = "etils" %}
{% set version = "1.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/etils/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 16245bce35a04b87cf24a345db76c60164107a338b95a4c153edc89adf4ab766

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.8,<4
  run:
    - python >={{ python_min }}


test:
  imports:
    - etils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/etils/
  summary: Collection of common python utils
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
    - traversaro
