{% set name = "etils" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/etils/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8ce810cc5eb80ab0c4cc9a2136f690df01c9cafc2d17188187cd05b00722bf8f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.11
    - flit-core >=3.8,<4
  run:
    - python >=3.11


test:
  imports:
    - etils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/etils/
  summary: Collection of common python utils
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
    - traversaro
