{% set name = "etils" %}
{% set version = "1.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  skip: true  #[py<310]
  url: https://github.com/google/etils/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 16245bce35a04b87cf24a345db76c60164107a338b95a4c153edc89adf4ab766

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python
    - flit-core >=3.8,<4
  run:
    - python

test:
  imports:
    - etils
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://etils.readthedocs.io
  summary: Collection of common python utils
  description: etils (eclectic utils) is an open-source collection of utils for python.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://etils.readthedocs.io
  dev_url: https://github.com/google/etils

extra:
  recipe-maintainers:
    - ngam
    - traversaro
