{% set name = "etils" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/etils/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d1fe37c1c7e52993962df3747ee9039fcc64e0482a9dd4bd0f2b1a2a3a0cdad2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - flit-core >=3.5,<4
  run:
    - python >=3.8


test:
  imports:
    - etils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/etils/
  summary: Collection of common python utils
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
