{% set name = "etils" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/etils/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 11e0503f8473f5c2f383c59435fea815c98289c8dcdd3d16d64f7fca2316b64e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core >=3.5,<4
  run:
    - python >=3.7


test:
  imports:
    - etils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/etils/
  summary: Collection of common python utils
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
